os: linux
dist: bionic
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
services:
  - docker
before_install:
  # - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk --assume-yes
  - sudo apt-get install bison build-essential g++-multilib git make python zip --assume-yes
  # download the TWRP Compressed Source Files from PhantomZone54's Release
  # Uncomment & Use below line If Building for Lollipop-based Devices
  # - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-5.1-norepo-20200222.tar.xz"
  # Use below line If Building for Marshmallow-based Devices
  # - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz"
  # Uncomment & Use below line If Building for Nougat-based Devices
  # - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-7.1-norepo-20200222.tar.xz"
  - wget https://getmyfile.xyz/dl_2228441/omni_twrp-5.1.1_cleaned.tar_0.xz -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  # Replace your tonystark-ab, ct744-twrp, celkon, ct744
  - cd $HOME/twrp/ 
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git $HOME/twrp/device/generic/twrpbuilder
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - cd device
  - wget https://getmyfile.xyz/dl_2227220/Celkon.zip
  - unzip Celkon
  - cd ..
  - export ALLOW_MISSING_DEPENDENCIES=true
  - source build/envsetup.sh
  - lunch omni_ct744-eng
  - make -j$(nproc --all) recoveryimage
  
